# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bc284575cf2881c971b7412af698e0135239cd8ef3e029a03130c3034b7c9abf5e5e7f08caeb430eae2be00a970ffd88490b2001df954acfc2ec9ec439ccc18

test:
  secret_key_base: 8c56651cf286c10ccbce7f12b9ce86d7f8aa0fbefc052c39eaf252877dcd1bd4d9413531c8c57b0865bed49305e013690f8bd9f70984d2ca5ee4713f81620935

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
